DEFAULT_FPGA_IP = "192.168.0.2"
DEFAULT_HOST_IP = "192.168.0.3"
DEFAULT_PORT = 8080

SEQ_ID_LEN = 4
DIGEST_LEN = 32
EXPECTED_REPLY_LEN = SEQ_ID_LEN + DIGEST_LEN

DEFAULT_MAX_CHUNK_SIZE = 1468
DEFAULT_MIN_CHUNK_SIZE = 512
DEFAULT_AVG_CHUNK_SIZE = 1024

DEFAULT_DB_PATH = "data/fingerprints.db"
DEFAULT_RESULT_DIR = "Result"
DEFAULT_WRITE_DIR = r"F:\Write_in"
